# bgp 模範解答: AS65001(r1) と AS65002(r2) を eBGP で接続し、各自のLANを広告
ha: ip addr add 10.1.0.10/24 dev eth1
ha: ip route replace default via 10.1.0.1
hc: ip addr add 10.2.0.10/24 dev eth1
hc: ip route replace default via 10.2.0.1
r1: ip addr add 10.1.0.1/24 dev eth1
r1: ip addr add 10.0.12.1/30 dev eth2
r2: ip addr add 10.0.12.2/30 dev eth1
r2: ip addr add 10.2.0.1/24 dev eth2
r1: vtysh -c 'conf t' -c 'router bgp 65001' -c 'no bgp ebgp-requires-policy' -c 'neighbor 10.0.12.2 remote-as 65002' -c 'network 10.1.0.0/24'
r2: vtysh -c 'conf t' -c 'router bgp 65002' -c 'no bgp ebgp-requires-policy' -c 'neighbor 10.0.12.1 remote-as 65001' -c 'network 10.2.0.0/24'
