# level09 模範解答
inet: ip addr add 163.172.250.1/28 dev eth1
inet: ip route add 11.0.0.0/25 via 163.172.250.12
inet: ip route add 12.0.0.0/25 via 163.172.250.12
r1: ip addr add 11.0.0.1/25 dev eth1
r1: ip addr add 163.172.250.12/28 dev eth2
r1: ip addr add 22.0.0.2/30 dev eth3
r1: ip route add 12.0.0.0/25 via 22.0.0.1
r1: ip route add 95.253.0.0/18 via 22.0.0.1
r1: ip route replace default via 163.172.250.1
r2: ip addr add 22.0.0.1/30 dev eth1
r2: ip addr add 12.0.0.1/25 dev eth2
r2: ip addr add 95.253.35.22/18 dev eth3
r2: ip route replace default via 22.0.0.2
a: ip addr add 11.0.0.2/25 dev eth1
a: ip route replace default via 11.0.0.1
b: ip addr add 11.0.0.3/25 dev eth1
b: ip route replace default via 11.0.0.1
c: ip addr add 12.0.0.2/25 dev eth1
c: ip route replace default via 12.0.0.1
d: ip addr add 95.253.35.1/18 dev eth1
d: ip route replace default via 95.253.35.22
